### PR TITLE
fix: map.replace #2253 (interceptors) #1980 (key order V5) 

### LINKED ISSUE #1980: ObservableMap.replace() - breaks entities order!
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Specifications

> The Map object holds key-value pairs and remembers the original insertion order of the keys.

The Map should guarantee the order of entities, but when I use method ObservableMap.replace() I got Map with broken order of entities.

The doc (https://mobx.js.org/refguide/map.html) says:

> replace(values). Replaces the entire contents of this map with the provided values. Short hand for .clear().merge(values)

So as I understand it should physically replace old Map by a new one, but in fact, it is trying to do a "smart" merge inside:

```
replace(values: ObservableMap<K, V> | IKeyValueMap<V> | any): ObservableMap<K, V> {
    transaction(() => {
        // grab all the keys that are present in the new map but not present in the current map
        // and delete them from the map, then merge the new map
        // this will cause reactions only on changed values
        const newKeys = (getMapLikeKeys(values) as any) as K[]
        const oldKeys = Array.from(this.keys())
        const missingKeys = oldKeys.filter(k => newKeys.indexOf(k) === -1)
        missingKeys.forEach(k => this.delete(k))
        this.merge(values)
    })
    return this
}
```

As a workaround I can use the following:

```
myMap.clear();
myMap.merge(newMap);
```

but it calls observe twice during one operation.

### LINKED ISSUE #2253: Change of behavior in ObservableMap.replace when using intercept in Mobx v4
### Version
Mobx: 4.13.1
Node: v13.2.0

### Issue
**Only in mobx4**

Following the changes in #1980 and #2003, visible in v4.13.1. We are facing a difference in the `replace` method of `ObservableMap` in v4.13.0.

When we `intercept` a change on a given property of the Map and **cancel it** (`return null`), the value is not set in the Map  (expected) but the `internal keys` array of the Map is updated with the name of the intercepted property. 

_**Change** the version of mobx to **4.13.0** to see the previous behavior_
[Code to reproduce](https://codesandbox.io/s/mobx-observable-map-replace-ts99u)

### PR DESCRIPTION
**Pull request by urugator**
Fixed #2253 
Fixed #1980 for V5 (it was fixed for V4)
Synced V4/V5 map tests.
Fixed deprecation warnings in V4 test.
Removed invalid use of `Object.entries` in V4 (`convertToMap`)

### CODE REVIEW

File: src/v4/utils/utils.ts [hunk 1]
```diff
@@ -108,13 +101,17 @@ export function isPlainObject(value) {
...
-export function convertToMap(dataStructure) {
+export function convertToMap(dataStructure: any): Map<any, any> {
     if (isES6Map(dataStructure) || isObservableMap(dataStructure)) {
         return dataStructure
     } else if (Array.isArray(dataStructure)) {
         return new Map(dataStructure)
     } else if (isPlainObject(dataStructure)) {
-        return new Map(Object.entries(dataStructure))
+        const map = new Map()
+        for (const key in dataStructure) {
```
Comment (mweststrate) [inline src/v4/utils/utils.ts]: use `forOf` here?

Comment (urugator) [reply src/v4/utils/utils.ts]: `forOf` is just a workaround for `Iterator`s - converting them to array is waste of resources and using `while` is PITA ... the function doesn't even accept/work with array/map/object.
Also I would prefer to keep this in sync with V5 (which intentionally doesn't have `forOf` util).

Comment (urugator) [reply src/v4/utils/utils.ts]: Basically the idea is: If you use `for of` in V5, use native `.forEach` (array/map/set) or `forOf` for iterators in V4... `forOf/for of` for `object` doesn't make sense...
