### PR TITLE
Fix #1653

### LINKED ISSUE #1653: issue with getting  observable array value
Hi,
i have a problem:
class userState {
@observable favourite = [ ];

@action
handleFavourite(credentials){
Fetcher.getFavourite(credentials).then(response => {

this.favourite = response.user.favourite ;
console.log(this.favourite) ;

})

} }

so the fetcher is a function that fetch some data and get a response (an array) and i want to store that data in an observable array and when i console log my observable array i don't get the value of the array, instead i have this on my console "Proxy { <target>: (5) […], <handler>: {…} }"

### LINKED ISSUE #2751: TypeError: Cannot convert a Symbol value to a string when making production build
**Intended outcome:**

I am able to compile my NextJS or other React project while `NODE_ENV=production`.

**Actual outcome:**

I receive the following error:

```
TypeError: Cannot convert a Symbol value to a string
    at b (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:1455)
    at n.i.O (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:40579)
    at Function.q [as u] (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:5046)
    at n.i.u (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:39408)
    at s (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:46570)
    at Array.forEach (<anonymous>)
    at exports.makeAutoObservable (/code/node_modules/mobx/dist/mobx.cjs.production.min.js:1:46618)
    at new config_ConfigStore (/code/.next/server/pages/_app.js:195:49)
    at new stores_RootStore (/code/.next/server/pages/_app.js:211:19)
    at Object.sYqq (/code/.next/server/pages/_app.js:223:15)
    at __webpack_require__ (/code/.next/server/pages/_app.js:23:31)
    at Module.1TCz (/code/.next/server/pages/_app.js:113:72)
    at __webpack_require__ (/code/.next/server/pages/_app.js:23:31)
    at Object.0 (/code/.next/server/pages/_app.js:99:18)
    at __webpack_require__ (/code/.next/server/pages/_app.js:23:31)
    at /code/.next/server/pages/_app.js:91:18
ierror Command failed with exit code 1.
```

**How to reproduce the issue:**

I've created a minimal example repository on GitHub that exhibits this behavior here: https://github.com/markrawls/mobx-symbol-error-example

If you manually downgrade MobX to 6.0.5 or 6.0.4, it works as expected. If you forcibly set `NODE_ENV=development` (or any non `production` string) for the build process, the build completes as expected. This is obviously suboptimal as we want to produce a production bundle.

**Versions**

The exclusively effects MobX 6.1.0. Downgrading to 6.0.4 or 6.0.5 resolves this issue.

### PR DESCRIPTION
**Pull request by urugator**
Fix error stringification on minified build
Fix `isObservableProp` not supporting `Symbols`
Fix `makeAutoObservable` not ignoring `inferredAnnotationsSymbol`
Fixes #2751

### CODE REVIEW

File: packages/mobx/__tests__/v5/base/make-observable.ts [hunk 1]
```diff
@@ -1409,3 +1410,16 @@ test("@override must override", () => {
         /^\[MobX\] 'Child\.prototype\.action' is decorated with 'override', but no such decorated member was found on prototype\./
     )
 })
+
+test("makeAutoObservable + production build #2751", () => {
+    const mobx = require(`../../../dist/mobx.cjs.production.min.js`)
```
Comment (iChenLei) [inline packages/mobx/__tests__/v5/base/make-observable.ts:1415]: Why we need require `mobx` from `dist` ?
```bash
 ✓ makeAutoObservable + production build #2751 (10 ms)
```
Btw I write the unit test, passed in current `main` branch.
So this unit test is test for what code change ? Looks like it's unuseful...  : (
