### PR TITLE
Fix type inference of observe function (Close #3179)

### LINKED ISSUE #3179: IObjectDidChange `type: "remove"` type annotation mismatch with `type="delete"`
**Intended outcome:**

The `observer` listener's event object's `type` should be inferred union of "add" | "update" | "delete", and I should not get a type error when trying perform a comparison on `type` against the `"delete"` value.

Screenshot_20211110_142742

**Actual outcome:**

Getting a type error because the actual value being provided by MobX's runtime can be `"delete"` -- whereas it is typed as `"remove"`. [`mobx/src/types/observableobject.ts#L70`](https://github.com/mobxjs/mobx/blob/6519021a3e2071189111be33aa9e05ab4188d76a/packages/mobx/src/types/observableobject.ts#L70) needs to be changed to `"delete"`

Screenshot_20211110_142251

**How to reproduce the issue:**

```typescript
observe(this.anythingObservable, (event) => {
  if (event.type === "delete") { ... }
})
```

To match the screenshot.

**Versions**

`mobx@6.3.6`

### PR DESCRIPTION
**Pull request by kubk**
### Code change checklist

-   [x] Added/updated unit tests
-   [ ] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [x] Verified that there is no significant performance drop (`npm run perf`)

Fixes: https://github.com/mobxjs/mobx/issues/3179

Both Map & Set resulted in wrong type inference. Now the correct type inference is covered with tests.

### CODE REVIEW

**Comment by urugator** [comment]
I assume  [`intercept`](https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/api/intercept.ts) has the same problem, could you take a look at it as well?

File: packages/mobx/src/api/observe.ts [hunk 1]
```diff
@@ -25,17 +25,17 @@ export function observe<T>(
     fireImmediately?: boolean
 ): Lambda
 export function observe<V>(
-    observableMap: ObservableSet<V>,
+    observableMap: ObservableSet<V> | Set<V>,
```
Comment (urugator) [inline packages/mobx/src/api/observe.ts:28]: Is the observable variant `ObservableSet/Map` even good for anything here? It implements `Set`...

Comment (mweststrate) [reply packages/mobx/src/api/observe.ts:28]: that seems problematic indeed, as `observableMap` would effectively become the least common denominator of both. Why was this needed?

Comment (urugator) [reply packages/mobx/src/api/observe.ts:28]: > Why was this needed?

In case you're asking about the need for `Set`/`Map`, there is an overload for object, which doesn't require `ObservableObject` but any `Object`:
```javascript
export function observe(
    object: Object,
    listener: (change: IObjectDidChange) => void,
    fireImmediately?: boolean
): Lambda
```
So Map/Set requires explicit cast to `ObservableMap/Set` otherwise it matches object overload. That's inconsistent and error prone.

Comment (mweststrate) [reply packages/mobx/src/api/observe.ts]: Check!

Comment (kubk) [reply packages/mobx/src/api/observe.ts]: @urugator Thanks, I've removed ObservableMap and ObservableSet from the typings. For some reason tests with ObservableMap pass but tests with ObservableSet don't:

image

This issue on CI: https://app.circleci.com/pipelines/github/mobxjs/mobx/1788/workflows/4a10412e-e197-4eea-bde8-3221d9b39c31/jobs/8295

I've double checked that both ObservableMap/ObservableSet implement ES6 versions. Both of them have same overload:

image

So the reason of issue is not clear. Workarounds:
- Return ObservableSet/ObservableMap back
- change unit test to match `ISetDidChange<any>`

Comment (mweststrate) [reply packages/mobx/src/api/observe.ts]: There are TS setups where Set/Map is not defined (based on the selected standard libs), so that union might not be that bad after all

Comment (urugator) [reply packages/mobx/src/api/observe.ts]: If that's the case I think a explanatory (or link) comment would be nice.

File: packages/mobx/__tests__/v5/base/typescript-tests.ts [hunk 2]
```diff
@@ -204,32 +208,6 @@ test("scope", () => {
...
-        return null
-    })
-    mobx.observe(ar2, (d: IArrayDidChange<number>) => {
-        // console.log(d.type)
-    })
-
-    const x: IObservableValue<number> = observable.box(3)
-})
-
-const state: any = observable({
```
Comment (kubk) [inline packages/mobx/__tests__/v5/base/typescript-tests.ts:229]: @urugator This variable isn't used anywhere. It also doesn't do anything useful because `observable` gets casted to `any`

File: packages/mobx/__tests__/v5/base/typescript-tests.ts [hunk 3]
```diff
@@ -204,32 +208,6 @@ test("scope", () => {
     t.equal(x3.z, 8)
 })
 
-test("typing", () => {
-    const ar: IObservableArray<number> = observable([1, 2])
-    mobx.intercept(ar, (c: IArrayWillChange<number> | IArrayWillSplice<number>) => {
```
Comment (kubk) [inline packages/mobx/__tests__/v5/base/typescript-tests.ts:209]: @urugator I've merged tests for intercept & observe into one test

File: packages/mobx/__tests__/v5/base/typescript-tests.ts [hunk 4]
```diff
@@ -278,6 +256,8 @@ test("box", () => {
     t.deepEqual(ar.slice(), [40, 20, 60, 210, 420])
     box.addSize()
     expect(ar.slice()).toEqual([40, 20, 60, 210, 420, 700])
+
+    const x: IObservableValue<number> = observable.box(3)
```
Comment (kubk) [inline packages/mobx/__tests__/v5/base/typescript-tests.ts:260]: This line was moved from the removed test above

**Comment by kubk** [comment]
@urugator I've fixed `intercept` typings and added the link to this discussion.

File: .changeset/moody-kids-punch.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"mobx": minor
```
Comment (urugator) [inline .changeset/moody-kids-punch.md:2]: Why not patch?

Comment (kubk) [reply .changeset/moody-kids-punch.md]: Agree, fixed

**Comment by urugator** [comment]
Thank you!
