### PR TITLE
fix #3669: SSR: `useSyncExternalStore` throws due to missing `getServerSnapshot`

### LINKED ISSUE #3669: `useSyncExternalStore` causes Error on Hydration of SSR React Page
**Intended outcome:**
MobX shouldn't throw an error and function as expected when part of a SSR stack. It should provide a `getServerSnapshot` parameter to the `useSyncExternalStore` call, which is required for hydrating pages.

**Actual outcome:**
Currently after the latest update (which to my knowledge moved MobX' React Integration to support `useSyncExternalStore` hydration of pages using MobX will cause

```
react-dom.development.js?ac89:16784 Uncaught Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
    at mountSyncExternalStore (react-dom.development.js?ac89:16784:1)
    at Object.useSyncExternalStore (react-dom.development.js?ac89:17727:1)
    at useSyncExternalStore (react.development.js?1b7e:1676:1)
    at useObserver (useObserver.js?cb83:74:25)
    at eval (observer.js?b6e3:42:27)
    at renderWithHooks (react-dom.development.js?ac89:16305:1)
    at updateFunctionComponent (react-dom.development.js?ac89:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js?ac89:19425:1)
    at updateMemoComponent (react-dom.development.js?ac89:19284:1)
    at beginWork (react-dom.development.js?ac89:21673:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4213:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4277:1)
    at beginWork$1 (react-dom.development.js?ac89:27451:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
```

**How to reproduce the issue:**
I have a fairly complex setup and sadly not enough time to provide a reproduction of the effect.
It occurs for me when I utilize the `observer(Component)` wrapper function, from what I can see.

**Versions**
4.0.2

### PR DESCRIPTION
**Pull request by urugator**

### CODE REVIEW

File: packages/mobx-react-lite/src/useObserver.ts [hunk 1]
```diff
@@ -5,6 +5,9 @@ import { isUsingStaticRendering } from "./staticRendering"
 import { observerFinalizationRegistry } from "./utils/observerFinalizationRegistry"
 import { useSyncExternalStore } from "use-sync-external-store/shim"
 
+// Required by SSR when hydrating #3669
+const getServerSnapshot = () => {}
```
Comment (mweststrate) [inline packages/mobx-react-lite/src/useObserver.ts:9]: I doubt that this is the intended snapshot, but no idea what else to put here, serializability is an assumption we cannot make true
