### PR TITLE
Fix: disable global state version usage in observer. Fixes #3728

### LINKED ISSUE #3728: [Bug] Error: Maximum update depth exceeded
**Intended outcome:**
Render without any issues

**Actual outcome:**
`Error: Maximum update depth exceeded.`

**How to reproduce the issue:**
Repro:
* Next.js https://stackblitz.com/edit/stackblitz-starters-wpvmwt?file=pages%2F_app.js
* Pure react https://stackblitz.com/edit/stackblitz-starters-aa5t8d?file=src%2Findex.tsx

1. `_app.jsx` - define the component as `observer`
2. `index.jsx` - use `useState` to store `mobx` store without lazy initialization (`useState(new Store())`)
4. App crashes because of `Maximum update depth exceeded`

Any component defined as `observer` higher in react tree than the defined `mobx` store is causing the issue above.

Lazy initialization (`useState(() => new Store())`), downgrading mobx-react-lite to 3.4.3  fixses issue or removing `observer` fixes issue.

**Versions**
mobx-react-lite@4.0.3

### PR DESCRIPTION
**Pull request by mweststrate**
This diff disables the usage of global state versioning. The reasoning here is:

* global state versioning is principle more correct
* effectively it doesn't make the implementation more compatible with concurrent mode, both implementations fail layer 3 compatibility
* in neither cases, the snapshot represents what actually will be read during render; as the latest version of all data is read, instead of the state described by the snapshot version. 
* since the local versioning approach doesn't break #3728 (for which could be argued it is unidiomatic), there seems at this moment little upside to the global version approach.

This PR deliberately doesn't clean up the underlying infra; the tracking of a global state version in the first place. I will probably put up a separate PR for that, but I also want to pursue more implementation solutions that might work better, that build on that infra.

### CODE REVIEW

**Comment by urugator** [comment]
I think you can remove:
```ts
// Provides ability to force component update without changing state version
const [, forceUpdate] = React.useState<Symbol>()
```
and change
```ts
               if (!adm.reaction) {
                    // We've lost our reaction and therefore all subscriptions, occurs when:
                    // 1. Timer based finalization registry disposed reaction before component mounted.
                    // 2. React "re-mounts" same component without calling render in between (typically <StrictMode>).
                    // We have to recreate reaction and schedule re-render to recreate subscriptions,
                    // even if state did not change.
                    createReaction(adm)
                    // Update version otherwise onStoreChange() would be ignored
                    adm.stateVersion = Symbol()
                    onStoreChange();
                }
```
I don't know if it's completely kosher to call `onStoreChange` during subscription, but IIRC it was working, the only problem was the call was ignored, because the version stayed the same, therefore the workaround with `forceUpdate`.

File: packages/mobx-react-lite/src/useObserver.ts [hunk 1]
```diff
@@ -69,7 +60,8 @@ export function useObserver<T>(render: () => T, baseComponentName: string = "obs
                     // even if state did not change.
                     createReaction(adm)
                     // `onStoreChange` won't force update if subsequent `getSnapshot` returns same value.
-                    forceUpdate(Symbol())
+                    // So we make sure that is not the case
+                    adm.stateVersion = Symbol()
```
Comment (urugator) [inline packages/mobx-react-lite/src/useObserver.ts:64]: Ehm, but you still have to call that `onStoreChange()` ... ?

Comment (mweststrate) [reply packages/mobx-react-lite/src/useObserver.ts:64]: No I don't think so, I think due to uSES getting a different version from getSnapshot, it will schedule update already itself. I guess React checks that?

Comment (mweststrate) [reply packages/mobx-react-lite/src/useObserver.ts:64]: (at least the test that failed without the forceUpdate, now succeeds again, the exact calling order of uSES remains a little mistery)

Comment (urugator) [reply packages/mobx-react-lite/src/useObserver.ts:64]: Ah, yea, I think you're correct, but then the comment on line 62 is perhaps a bit misleading.

Comment (mweststrate) [reply packages/mobx-react-lite/src/useObserver.ts:64]: ah yeah, didn't clean that up properly, will do in the cleanup branch
